# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93615cd8dd32e5b2f3c5b9ab17ba48d2cd15e81cccd0921f564325e4f5063c47fbe3c21d91f9ff6fb2639b9036677b80d91671f58a385608df889094949e323d

test:
  secret_key_base: 9da39662579d6d1d4f1e652b81956db82d7c2355039f8a3d607547d40319963e25b034fa2df4c7142b862270d14eb71cc4a65b33117c6c2b7ba1b7b86a7d28dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
